version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    working_dir: "/app"
    volumes:
      - ./:/app
    tty: true
    environment:
    - HOST=0.0.0.0
    - CHOKIDAR_USEPOLLING=true
    command: yarn run dev